### PR TITLE
fixes in SECURITY.md

### PR DESCRIPTION
**Pull request by dd-dreams**

### CODE REVIEW

**Comment by squell** [comment]
This makes the Markdown look nicer, but it also has the effect of actually invalidating the PGP signature on it.

**Review by squell — DISMISSED** [review]
This makes the Markdown look nicer (and fixes some typos that need fixing), but it also has the effect of actually invalidating the PGP signature on it; it would be better to remove it. We can of course discuss the relative merits of a digital signature vs. aesthetics.

Could you re-do this PR with the PGP signature removed entirely?

**Comment by dd-dreams** [comment]
Sure.

**Comment by dd-dreams** [comment]
You're right about removing the signature. There is no need to sign this document, as it doesn't contain any sensitive information.

**Review by squell — APPROVED** [review]

**Pull request merged**
